# Generated by Django 5.0.3 on 2024-03-29 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_proj_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
    ]
